spring.application.name=demo

spring.datasource.url=jdbc:postgresql://dpg-d8a0on8g4nts73d307g0-a/hospital_db_r3zv

spring.datasource.username=hospital_user

spring.datasource.password=5WTP2dBckmWBNfHDRERsdpoj01XfAWXK

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false