spring.application.name=demo

spring.datasource.url=${postgresql://hospital_user:5WTP2dBckmWBNfHDRERsdpoj01XfAWXK@dpg-d8a0on8g4nts73d307g0-a/hospital_db_r3zv}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false